/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {"inverse-surface": "var(--color-inverse-surface)", "surface-container-lowest": "var(--color-surface-container-lowest)", "error": "var(--color-error)", "tertiary": "var(--color-tertiary)", "surface-variant": "var(--color-surface-variant)", "outline": "var(--color-outline)", "on-secondary": "var(--color-on-secondary)", "on-secondary-container": "var(--color-on-secondary-container)", "surface-container-highest": "var(--color-surface-container-highest)", "background": "var(--color-background)", "secondary": "var(--color-secondary)", "primary-fixed-dim": "var(--color-primary-fixed-dim)", "error-container": "var(--color-error-container)", "primary": "var(--color-primary)", "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)", "on-tertiary-container": "var(--color-on-tertiary-container)", "secondary-fixed": "var(--color-secondary-fixed)", "tertiary-container": "var(--color-tertiary-container)", "surface": "var(--color-surface)", "on-primary-fixed": "var(--color-on-primary-fixed)", "primary-container": "var(--color-primary-container)", "surface-container-low": "var(--color-surface-container-low)", "surface-dim": "var(--color-surface-dim)", "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)", "on-background": "var(--color-on-background)", "inverse-on-surface": "var(--color-inverse-on-surface)", "on-surface-variant": "var(--color-on-surface-variant)", "on-surface": "var(--color-on-surface)", "on-tertiary-fixed": "var(--color-on-tertiary-fixed)", "inverse-primary": "var(--color-inverse-primary)", "tertiary-fixed": "var(--color-tertiary-fixed)", "surface-bright": "var(--color-surface-bright)", "surface-container-high": "var(--color-surface-container-high)", "outline-variant": "var(--color-outline-variant)", "on-primary": "var(--color-on-primary)", "surface-container": "var(--color-surface-container)", "secondary-container": "var(--color-secondary-container)", "on-error-container": "var(--color-on-error-container)", "on-tertiary": "var(--color-on-tertiary)", "primary-fixed": "var(--color-primary-fixed)", "on-primary-container": "var(--color-on-primary-container)", "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)", "on-secondary-fixed": "var(--color-on-secondary-fixed)", "secondary-fixed-dim": "var(--color-secondary-fixed-dim)", "on-error": "var(--color-on-error)", "surface-tint": "var(--color-surface-tint)", "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)"},
      "borderRadius": { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      "spacing": { "space-lg": "1.5rem", "margin-desktop": "2rem", "margin": "1rem", "gutter": "1rem", "space-xs": "0.25rem", "gutter-desktop": "1.5rem", "space-sm": "0.5rem", "space-xl": "2.5rem", "space-md": "1rem" },
      "fontFamily": { "headline-sm": ["Newsreader"], "display-lg-mobile": ["Newsreader"], "body-md": ["Inter"], "headline-md": ["Newsreader"], "label-sm": ["Inter"], "body-lg": ["Inter"], "label-md": ["Inter"], "numeric-md": ["Inter"], "body-sm": ["Inter"], "display-lg": ["Newsreader"], "numeric-lg": ["Inter"], "numeric-sm": ["Inter"], "headline-lg": ["Newsreader"] },
      "fontSize": { "headline-sm": ["1.125rem", { "lineHeight": "1.625rem", "fontWeight": "500" }], "display-lg-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.01em", "fontWeight": "600" }], "body-md": ["0.875rem", { "lineHeight": "1.375rem", "fontWeight": "400" }], "headline-md": ["1.375rem", { "lineHeight": "1.875rem", "letterSpacing": "-0.01em", "fontWeight": "500" }], "label-sm": ["0.6875rem", { "lineHeight": "0.875rem", "letterSpacing": "0.04em", "fontWeight": "600" }], "body-lg": ["1rem", { "lineHeight": "1.5rem", "fontWeight": "400" }], "label-md": ["0.8125rem", { "lineHeight": "1.125rem", "letterSpacing": "0.01em", "fontWeight": "500" }], "numeric-md": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "500" }], "body-sm": ["0.75rem", { "lineHeight": "1.125rem", "fontWeight": "400" }], "display-lg": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "600" }], "numeric-lg": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.02em", "fontWeight": "600" }], "numeric-sm": ["0.75rem", { "lineHeight": "1rem", "fontWeight": "500" }], "headline-lg": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.015em", "fontWeight": "600" }] }
    },
  },
  plugins: [],
}
